name: Deploy to Amazon ECS1

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-north-1                   # set this to your preferred AWS region
  ECR_REPOSITORY: 180294207856.dkr.ecr.eu-north-1.amazonaws.com/master  # Amazon ECR repository name
  IMAGE_TAG: latest  # Set a generic variable for the image tag

permissions:
  contents: read

jobs:
  push-to-ecr:
    name: Push to Amazon ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_TAG
